angular.module('templates-app', ['toolbar/common/changelistitem.tpl.html', 'toolbar/loggedout/loggedout.tpl.html', 'toolbar/nointernet/nointernet.tpl.html', 'toolbar/nolocalhost/nolocalhost.tpl.html', 'toolbar/noproject/noproject.tpl.html', 'toolbar/noseat/noseat.tpl.html', 'toolbar/project/conflicts/conflicts.tpl.html', 'toolbar/project/preparing/preparing.tpl.html', 'toolbar/project/progress/progress.tpl.html', 'toolbar/project/publish/publish.tpl.html', 'toolbar/project/publish/publishitem.tpl.html', 'toolbar/project/update/update.tpl.html', 'toolbar/project/uptodate/uptodate.tpl.html', 'toolbar/project/working/working.tpl.html', 'toolbar/refreshproject/refreshproject.tpl.html', 'toolbar/root/root.tpl.html']);

angular.module("toolbar/common/changelistitem.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/common/changelistitem.tpl.html",
    "<div ng-mouseover=\"mouseover()\" ng-mouseleave=\"mouseleave()\" ng-disabled=\"resolved\"><div><div class=\"list-item-icon file\" ng-class=\"{conflict: item.isConflict, resolved: item.isResolved}\"></div><div class=\"list-item-details\"><div ng-if=\"!showMessage()\"><div class=\"list-item-title\" ng-bind=\"item.path | filename\"></div><div class=\"list-item-info\" ng-bind=\"item.path\"></div></div><div ng-if=\"showMessage()\" class=\"list-item-message\"><div class=\"conflict-message-text\" ng-bind=\"message\"></div><div class=\"conflict-message-tools\"><button class=\"conflict-button cancel\" analytics-on=\"click\" analytics-event=\"ConflictCancel\" analytics-category=\"Toolbar\" analytics-label=\"Cancel On Conflict Dialog\" ng-click-once=\"closeMessage()\" ng-bind=\"cancel\"></button> <button class=\"conflict-button ok\" analytics-on=\"click\" analytics-event=\"ConflictTheirs\" analytics-category=\"Toolbar\" analytics-label=\"Take Theirs Conflict Dialog\" ng-if=\"confirm\" ng-click-once=\"theirsConfirmed()\">Yes</button></div></div></div></div><div class=\"conflict-tools\" ng-if=\"showEdit()\"><button class=\"showDiff\" ng-click-once=\"showDiff()\" analytics-on=\"click\" analytics-event=\"ConflictDiff\" analytics-category=\"Toolbar\" analytics-label=\"Show Diff On Conflict Dialog\" uc-tooltip=\"See differences\"><i uc-icon=\"collab/eye\"></i></button> <button class=\"externalMerge\" ng-click-once=\"externalMerge()\" analytics-on=\"click\" analytics-event=\"ConflictMerge\" analytics-category=\"Toolbar\" analytics-label=\"Merge On Conflict Dialog\" uc-tooltip=\"Launch external tool\"><i uc-icon=\"collab/external_merge\"></i></button> <button class=\"mine\" ng-click-once=\"mine()\" analytics-on=\"click\" analytics-event=\"ConflictMine\" analytics-category=\"Toolbar\" analytics-label=\"Choose Mine On Conflict Dialog\" uc-tooltip=\"Choose mine\"><i uc-icon=\"collab/choose_mine\"></i></button> <button class=\"theirs\" ng-click-once=\"theirs()\" analytics-on=\"click\" analytics-event=\"ConflictTheirs\" analytics-category=\"Toolbar\" analytics-label=\"Choose Theirs On Conflict Dialog\" uc-tooltip=\"Choose theirs\"><i uc-icon=\"collab/choose_theirs\"></i></button></div></div>");
}]);

angular.module("toolbar/loggedout/loggedout.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/loggedout/loggedout.tpl.html",
    "<div class=\"hero-panel\"><div class=\"header\"><div class=\"header-content\"><i class=\"icon-attention\"></i><span class=\"text\">You are logged out</span></div></div><div class=\"content\"><p class=\"message\">Sign in to access Collaborate</p><button type=\"button\" class=\"btn btn-success action\" ng-click=\"login()\" analytics-on=\"click\" analytics-event=\"Login\" analytics-category=\"Toolbar\" analytics-label=\"Sign In From Logged Out\">Sign in...</button></div></div>");
}]);

angular.module("toolbar/nointernet/nointernet.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/nointernet/nointernet.tpl.html",
    "<div class=\"no-internet hero-panel\"><div class=\"header\">Service Unavailable</div><div class=\"panel-body content-centered\"><div class=\"error-dialog centered-content\"><div uc-icon=\"collab/no_internet\"></div><div class=\"message\">No Internet Connection</div></div></div></div>");
}]);

angular.module("toolbar/nolocalhost/nolocalhost.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/nolocalhost/nolocalhost.tpl.html",
    "<div class=\"header\">Localhost Unavailable</div><div class=\"hero-icon warning\">&#x26A0;</div><div class=\"hero-text center\">Collaborate was unable to establish a connection to Unity. <span ng-if=\"localUrl\">Please ensure you are able to visit <i ng-bind=\"localUrl\"></i> in your browser and reopen the project.</span></div>");
}]);

angular.module("toolbar/noproject/noproject.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/noproject/noproject.tpl.html",
    "<div class=\"header\"><button class=\"ut-button-flat primary\" ng-click=\"onEnableCollab()\" analytics-on=\"click\" analytics-event=\"StartNow\" analytics-category=\"Toolbar\" analytics-label=\"Start Now\">Start now!</button></div><div class=\"header-arrow-up\"></div><div uc-icon=\"collab/cloud\" class=\"hero-icon\"></div><div class=\"hero-text center\"><p ng-if=\"userMessageInnerHTML\" ng-bind-html=\"userMessageInnerHTML\"></p><p ng-if=\"userMessage\">{{userMessage}}</p></div>");
}]);

angular.module("toolbar/noseat/noseat.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/noseat/noseat.tpl.html",
    "<div class=\"hero-panel\"><div class=\"header\"><div class=\"header-content\"><i class=\"icon-attention\"></i><span class=\"text\">Requires Unity Teams</span></div></div><div class=\"content\"><p class=\"message\">Ask the organization owner for access to Unity Teams</p></div><div class=\"footer\"><div class=\"wrapper\"><span class=\"footnote\"><button class=\"refresh\" ng-click=\"requestUnityTeamsStatus()\">Refresh</button> if you&#39;ve recently received access.</span> <a class=\"ut-button-text\" ng-click=\"openSeatInfoUrl()\">Learn More<i class=\"icon-outbound\"></i></a></div></div></div>");
}]);

angular.module("toolbar/project/conflicts/conflicts.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/conflicts/conflicts.tpl.html",
    "<div class=\"update-info\" ng-if=\"needsUpdate\">New revision on the server, <a class=\"update-info-link\" ng-click=\"onUpdate()\" analytics-on=\"click\" analytics-event=\"UpdateConflict\" analytics-category=\"Toolbar\" analytics-label=\"Update in Conflict Screen\">update now</a></div><div class=\"header\"><div><div>There were merge conflicts!</div></div></div><div class=\"header-arrow-down\"></div><div class=\"scrollable\"><div class=\"subheading\"><ng-pluralize count=\"conflictCount\" when=\"{'one': '{{conflictCount}} Conflicting file', 'other': '{{conflictCount}} Conflicting files'}\"></ng-pluralize><div class=\"pull-right\"><a ng-click=\"seeAll()\">See all in project</a></div></div><div class=\"list\"><uc-changelist-item item=\"change\" on-update=\"rebuildChanges\" class=\"list-item common\" ng-repeat=\"change in conflictChanges\"></uc-changelist-item></div></div>");
}]);

angular.module("toolbar/project/preparing/preparing.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/preparing/preparing.tpl.html",
    "<div class=\"hero-panel\"><div class=\"header\"><div class=\"header-content\"><i class=\"icon-collaborate-timer\"></i><span class=\"text\">Please wait</span></div></div><div class=\"content\"><p class=\"message\">Scanning project...</p></div></div>");
}]);

angular.module("toolbar/project/progress/progress.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/progress/progress.tpl.html",
    "<div class=\"header\" ng-bind=\"title\"></div><div class=\"header-arrow-up\"></div><div class=\"panel-progress\"><div class=\"outer-progress\"><div round-progress max=\"max\" current=\"current\" color=\"#0cb4cc\" bgcolor=\"#000000\" radius=\"80\" stroke=\"6\" semi=\"false\" rounded=\"false\" clockwise=\"true\" responsive=\"false\" duration=\"800\" animation=\"easeInOutQuart\" animation-delay=\"0\"></div><div class=\"progress-percent\" ng-bind=\"info\"></div></div><a class=\"btn-small\" ng-click=\"doCancel()\" ng-class=\"{'btn-disabled':working || !canCancel}\" analytics-on=\"click\" analytics-event=\"CancelOperation\" analytics-category=\"Toolbar\" analytics-label=\"Cancel Operation\">Cancel</a></div>");
}]);

angular.module("toolbar/project/publish/publish.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/publish/publish.tpl.html",
    "<div class=\"publish\"><div class=\"header\"><textarea autofocus ng-trim=\"false\" ng-keydown=\"allowTabs($event)\" ng-model=\"$storage.comment\" id=\"user-comment\" placeholder=\"Describe your changes here\"></textarea><button ng-hide=\"isFiltered\" class=\"ut-button-flat primary\" ng-click=\"onPublish(false)\" analytics-on=\"click\" analytics-event=\"Publish\" analytics-category=\"Toolbar\" analytics-label=\"Publish Changes\">{{publishButtonLabel}}</button> <button ng-show=\"isFiltered\" class=\"ut-button-flat primary\" ng-click=\"onPublish(true)\" analytics-on=\"click\" analytics-event=\"Publish\" analytics-category=\"Toolbar\" analytics-label=\"Publish Selected\">Publish Selected ({{changelist.length}})</button></div><div class=\"header-arrow-up\"></div><div class=\"scrollable\"><div class=\"list\" md-virtual-repeat-container id=\"vertical-container\"><div class=\"subheading\"><a ng-show=\"isFiltered\" ng-click=\"clearSelection()\">&#x24e7; clear selection</a><ng-pluralize ng-hide=\"isFiltered\" count=\"changelist.length\" when=\"{'one': 'One Change', 'other': '{{changelist.length}} Changes'}\"></ng-pluralize><div class=\"pull-right\"><a ng-hide=\"isFiltered\" ng-click=\"seeAll()\">See all in project</a></div></div><div class=\"list-item local-change group\" md-virtual-repeat=\"localChange in dynamicChanges\" md-on-demand><uc-publish-item local-change=\"localChange\"></uc-publish-item></div></div></div></div>");
}]);

angular.module("toolbar/project/publish/publishitem.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/publish/publishitem.tpl.html",
    "<div class=\"container-content\"><div class=\"list-item-icon\" ng-class=\"getClass()\"></div><div class=\"list-item-details\"><div ng-if=\"!revertListItem\"><div class=\"list-item-title\" ng-if=\"!localChange.isFolderMeta && !localChange.isMeta\" ng-bind=\"localChange.path | filename\"></div><div class=\"list-item-title\" ng-if=\"!localChange.isFolderMeta && localChange.isMeta\" ng-bind=\"localChange.path | filename | stripExtension\"></div><div class=\"list-item-info file\" ng-if=\"!localChange.reverting && !localChange.isFolderMeta && !localChange.isMeta\" ng-bind=\"localChange.path\"></div><div class=\"list-item-info file\" ng-if=\"!localChange.reverting && !localChange.isFolderMeta && localChange.isMeta\" ng-bind=\"localChange.path | stripExtension\"></div><div class=\"list-item-info folder\" ng-if=\"!localChange.reverting && localChange.isFolderMeta\" ng-bind=\"localChange.path | stripExtension\"></div><div ng-show=\"localChange.reverting\">Reverted</div></div><div class=\"confirm-revert-text\" ng-if=\"revertListItem\">{{revertMessage()}}</div></div><button ng-if=\"revertListItem && localChange.isRevertable\" class=\"confirm-revert-button\" ng-click=\"revertFile(localChange)\" analytics-on=\"click\" analytics-event=\"ConfirmY\" analytics-category=\"Toolbar\" analytics-label=\"Confirm revert (Yes) \">Yes!</button> <button ng-if=\"revertListItem && localChange.isRevertable\" class=\"confirm-revert-button\" ng-click=\"cancelRevert(localChange)\" analytics-on=\"click\" analytics-event=\"ConfirmN\" analytics-category=\"Toolbar\" analytics-label=\"Confirm revert (No)\">No</button> <button ng-if=\"revertListItem && !localChange.isRevertable\" class=\"confirm-revert-button\" ng-click=\"cancelRevert(localChange)\" analytics-on=\"click\" analytics-event=\"ConfirmO\" analytics-category=\"Toolbar\" analytics-label=\"Confirm revert (OK)\">Ok</button><div class=\"publish-tools\" ng-if=\"!localChange.reverting && !revertListItem\"><button class=\"showDiff\" uc-icon=\"collab/eye\" uc-tooltip=\"See differences\" ng-click=\"showDiff(localChange)\" analytics-on=\"click\" analytics-event=\"DiffShow\" analytics-category=\"Toolbar\" analytics-label=\"Show Diff\"></button> <button class=\"revert\" uc-icon=\"collab/revert\" uc-tooltip=\"Revert asset\" ng-click=\"askRevert(localChange)\" analytics-on=\"click\" analytics-event=\"DiffHide\" analytics-category=\"Toolbar\" analytics-label=\"Ask For Revert\"></button></div></div>");
}]);

angular.module("toolbar/project/update/update.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/update/update.tpl.html",
    "<div class=\"header\"><button ng-click=\"onUpdate()\" class=\"ut-button-flat primary\" analytics-on=\"click\" analytics-event=\"Update\" analytics-category=\"Toolbar\" analytics-label=\"Update Now\">Update now!</button></div><div class=\"header-arrow-down\"></div><div class=\"scrollable\"><div class=\"subheading\"><ng-pluralize count=\"revisionAvailable()\" when=\"{'0': 'No revision available.',\n" +
    "	                     'one': '1 revision available.',\n" +
    "	                     'other': '{} revisions available.'}\"></ng-pluralize></div><div class=\"list\"><div class=\"list-item group common\" ng-repeat=\"revision in revisions | filter: missingFilter\" ng-click=\"showRevision(revision)\"><div class=\"list-item-details\"><div class=\"list-item-title\"><strong>#{{revisions.length - revisions.indexOf(revision)}} -</strong> {{revision.author.name}} <small><time-ago from-time=\"{{revision.committed_date}}\"></time-ago></small></div><div ng-mouseover=\"scrollElement($event)\" ng-mouseleave=\"unscrollElement($event)\" class=\"list-item-info\" ng-bind=\"revision.comment\"></div></div></div></div></div>");
}]);

angular.module("toolbar/project/uptodate/uptodate.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/uptodate/uptodate.tpl.html",
    "<div class=\"header\">You are up to date!</div><div class=\"uptodate hero-content\"><div uc-icon=\"collab/up_to_date\" class=\"hero-icon\"></div><span ng-if=\"false\">#32</span></div><div class=\"hero-text\"><strong ng-bind=\"revisionInfo.author.name\"></strong> <small><time-ago from-time=\"{{revisionInfo.committed_date}}\"></time-ago></small><p ng-bind=\"revisionInfo.comment\"></p></div>");
}]);

angular.module("toolbar/project/working/working.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/project/working/working.tpl.html",
    "<div class=\"hero-panel\"><div class=\"header\"><div class=\"header-content\"><i class=\"icon-collaborate-timer\"></i><span class=\"text\">Please wait</span></div></div><div class=\"content\"><p class=\"message\">Putting in the final touches...</p></div></div>");
}]);

angular.module("toolbar/refreshproject/refreshproject.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/refreshproject/refreshproject.tpl.html",
    "<div class=\"hero-panel\"><div class=\"header\"><div class=\"header-content\"><i class=\"icon-attention\"></i><span class=\"text\">Link Lost</span></div></div><div class=\"content\"><p class=\"message\">Unity seems to have lost its link to your project</p><button type=\"button\" class=\"btn btn-success action\" ng-click=\"onGoToHub()\" analytics-on=\"click\" analytics-event=\"MoreInfo\" analytics-category=\"Toolbar\" analytics-label=\"Link Lost Info\">More Info</button></div></div>");
}]);

angular.module("toolbar/root/root.tpl.html", []).run(["$templateCache", function ($templateCache) {
  $templateCache.put("toolbar/root/root.tpl.html",
    "<div class=\"pane\"><div class=\"content\" ui-view></div><div class=\"footer\" ut-disabled-all=\"hideFooter\"><div><div class=\"tools\"><button ng-click=\"onGoToHistory()\" uc-icon=\"collab/history\" uc-tooltip=\"View History\" analytics-on=\"click\" analytics-event=\"OpenHistory\" analytics-category=\"Toolbar\" analytics-label=\"Opened history from toolbar\"></button> <button ng-click=\"onGoToMembers()\" uc-icon=\"collab/invite\" uc-tooltip=\"Invite Teammate\" analytics-on=\"click\" analytics-event=\"OpenMembers\" analytics-category=\"Toolbar\" analytics-label=\"Opened members in web dashboard from toolbar\"></button></div><div class=\"tools\" ng-hide=\"true\"><button ng-click=\"onGoToSettings()\" uc-icon=\"collab/menu\" uc-tooltip=\"More Info\" analytics-on=\"click\" analytics-event=\"OpenSettings\" analytics-category=\"Toolbar\" analytics-label=\"Opened settings from toolbar\"></button></div></div><div class=\"right-tools\"><div class=\"message\">Missing changes? Click to rescan</div><div class=\"tools\"><button ng-click=\"startGetChanges()\" uc-icon=\"collab/update\" uc-tooltip=\"Rescan\" analytics-on=\"click\" analytics-event=\"GetChanges\" analytics-category=\"Toolbar\" analytics-label=\"Triggered get changes from toolbar\"></button></div></div></div></div>");
}]);
